### ISSUE TITLE
[Feature] Add deployment info on UI

### ISSUE THREAD

**Issue by jcace** [application-research/delta-nextjs-client#12]
Query the `/api/v1/health` endpoint, and display the response somewhere in the UI 
- node UUID field is useful to debug the exact instance of delta that's running
- DDM info (version/commit hash) useful to determine code running for DDM
- Delta info (version/commit hash) useful to determine code running for Delta

see api response: https://github.com/application-research/delta/pull/63

This can be a small info that the user can copy from a textarea. It'll help us (support) to look into the content of a given delta node in case we need to investigate some issues.

**Comment by elijaharita** [comment]
this was added to the top of the ui in low contrast text, lmk  if that is ok or if you would prefer something else

**Comment by jcace** [comment]
Looks awesome! 

I might tweak it to make the text even a bit smaller, just to really de-emphasize. But your call

**Comment by elijaharita** [comment]
i will do that
