### ISSUE TITLE
[Feature] Provider - allow enabling/disabling self-service, changing name

### ISSUE THREAD

**Issue by jcace** [application-research/delta-nextjs-client#14]
Update the Providers ui to allow the user to enable or disable the self-service for that provider, as well as changing the friendly name.

This will be controlled by a boolean flag `allow_self_service` on the provider - true = enabled, false = disabled.

If self service is disabled, the provider's API key/UUID could be hidden as it's not relevant unless enabled.

**Comment by jcace** [comment]
API request to update it :

POST `/api/v1/providers/f012345`

**body:**
```json
{
		"actor_name": "jason",
		"allow_self_service": true
}
```

**Comment by elijaharita** [comment]
done
