### ISSUE TITLE
[Bug] Attach content to dataset - issues

### ISSUE THREAD

**Issue by jcace** [application-research/delta-nextjs-client#17]
1. When "Attach content" is clicked for a specific dataset, it should populate the **dataset name** field - user should not have to type it in. Also should be a dropdown for other cases 
<img width="260" alt="Screenshot 2023-03-27 at 12 25 14 PM" src="https://user-images.githubusercontent.com/12418265/228045767-67c6941e-536d-45df-9edb-9f7819e864bf.png">

2. The UX around "Paste content file here" is difficult - when clicked on, the user is expected to just "ctrl-V" their clipboard and hope it works - but they don't know if they pasted the correct thing, or if it was validated correctly, etc. Would be be better to pop open a big text modal so they can see the JSON before submitting. Or, just accept a file upload where they select a .json file from their filesystem and the UI parses it.

3. There's no feedback when the user clicks Upload - should show loading, and then the results (which CIDs were successful, and which ones failed). Right now it just does nothing, but the response provides a list of what succeeded and what failed.

**Comment by elijaharita** [comment]
for tracking: issue 1 and 2 have been fixed

3 in progress

**Comment by elijaharita** [comment]
holy moly it was a bit of an adventure but i almost have 3 done. probably tomorrow

**Comment by jcace** [comment]
@elijaharita  Not sure if this was also captured but the modal doesn't close after successfully importing content. It just stays open like this:

<img width="391" alt="Screenshot 2023-04-26 at 11 49 28 AM" src="https://user-images.githubusercontent.com/12418265/234674014-ade32f26-6e26-40bd-8626-b932d7e7be29.png">
