### ISSUE TITLE
[Feature] Datasets page - add count of contents per dataset

### ISSUE THREAD

**Issue by jcace** [application-research/delta-nextjs-client#9]
(will require some backend work). Add another column that is # of content pieces, in addition to # of bytes, for each dataset

Also I think we can remove the `id` column from this page too.

**Comment by elijaharita** [comment]
@jcace does this still require backend work or is it ready?

**Comment by jcace** [comment]
@elijaharita Just added it here: https://github.com/application-research/delta-dm/commit/bead9221cf77f0bee99eae5b62df8241284c90e1 

should be good to go!
